- pom.xml
> Tommaso peletta

- items-service/src/main/resources/META-INF/load.sql
- web-ui/src/app/pages/auth/auth.component.html
- web-ui/src/app/pages/catalogue/filters/filters.component.html
- web-ui/src/app/pages/catalogue/filters/filters.component.ts
- web-ui/src/app/pages/catalogue/list-items/list-items.component.ts
- web-ui/src/app/services/catalogue.service.ts
Affinage du code web/ui et load.sql.
Enlever du code en commentaire et implementation de la recherche par etat
> Affinage du code web/ui

- web-ui/src/app/app.module.ts
- web-ui/src/app/pages/catalogue/body-catalogue/body-catalogue.component.html
- web-ui/src/app/pages/catalogue/filters/filters.component.html
- web-ui/src/app/pages/catalogue/filters/filters.component.ts
- web-ui/src/app/pages/catalogue/list-items/list-items.component.html
- web-ui/src/app/pages/nav-bar/nav-bar.component.html
Add the fonctionnality of research with the price. PriceFrom and PriceTo
> Patrick sardinha

- .travis.yml
- items-service/src/main/java/api/ItemRestService.java
> travis modification

- statistic-service/src/main/java/domain/service/StatisticServiceImpls.java
> fix Random security issue

- items-service/src/main/java/api/ItemRestService.java
- statistic-service/src/main/java/domain/model/StatisticItem.java
- statistic-service/src/main/java/domain/model/StatisticUser.java
- statistic-service/src/main/java/domain/service/StatisticServiceImpls.java
- statistic-service/src/test/java/domain/service/StatisticServiceImplTest.java
- user-service/src/main/java/api/UserRestService.java
> fix code smells

- items-service/src/main/java/domain/service/ItemServiceImpl.java
- items-service/src/test/java/domain/service/ItemServiceImplTest.java
add case insensivity to getbysearch methode in item-service
> add case insensivity

- ad-service/src/main/java/api/AnnonceRestService.java
- ad-service/src/main/java/domain/model/Annonce.java
- ad-service/src/main/java/domain/service/AnnonceService.java
- ad-service/src/main/java/domain/service/AnnonceServiceImpl.java
- ad-service/src/test/java/domain/service/AnnonceServiceImplTest.java
- items-service/src/main/java/api/ItemRestService.java
- items-service/src/main/java/domain/model/Item.java
- items-service/src/main/java/domain/service/ItemService.java
- items-service/src/main/java/domain/service/ItemServiceImpl.java
- items-service/src/test/java/domain/service/ItemServiceImplTest.java
PUT pour update et remove item service et ad service, le remove change le flag de state en state * 10 pour que l'on garde une trace de l'etat de l'objet, donc 10 = objet abimé vendu, 20 bon état vendu et 30 neuf vendu 
Pour une raison inconnu je n'ai pas pu lancer le item service à cause de kafka, mais le build fonctionne, il se peut juste  qu'il y ait des erreurs pour les requetes, mais normalement non, puisque tout fonctionne sur ad service.
> Guillaume comte

- web-ui/src/app/app.module.ts
- web-ui/src/app/pages/messagerie/messagerie.component.html
- web-ui/src/app/pages/messagerie/messagerie.component.ts
> fix merge conflict

- web-ui/src/app/app.module.ts
- web-ui/src/app/pages/page-discussion/page-discussion.component.html
- web-ui/src/app/pages/page-discussion/page-discussion.component.spec.ts
- web-ui/src/app/pages/page-discussion/page-discussion.component.ts
I created the discussion-page (in which people will discuss). This is only the model for the moment. It is not fully functional as we don't have the messenger microservice yet.
> add discussion page

- web-ui/src/app/services/keycloak.service.ts
Fix issue path and import keycloak-js
> fix keycloak issue

- statistic-service/src/test/java/domain/service/StatisticServiceImplTest.java
fix statistic test issue after persistent database
> fix test issue

- items-service/src/main/java/api/ItemRestService.java
- items-service/src/main/java/domain/model/Item.java
- items-service/src/main/java/domain/service/ItemService.java
- items-service/src/main/java/domain/service/ItemServiceImpl.java
- items-service/src/test/java/domain/service/ItemServiceImplTest.java
- statistic-service/src/test/java/domain/service/StatisticServiceImplTest.java
fix code smell and add few test in item-service
> fix code smell

- web-ui/src/app/app.component.ts
- web-ui/src/app/pages/home/carousel-item/carousel-item.component.html
- web-ui/src/app/services/keycloak.interceptor.service.ts
- web-ui/src/app/services/keycloak.service.spec.ts
- web-ui/src/app/services/keycloak.service.ts
- web-ui/src/environments/environment.ts
- web-ui/src/main.ts
> modif fix keycloak

- docker-compose/docker-compose-microservices.yml
- docker-compose/docker-compose-server.yml
put messenger to docker-compose and update docker-compose-server
> update server docker compose

- web-ui/src/app/pages/messagerie/messagerie.component.html
- web-ui/src/app/pages/messagerie/messagerie.component.ts
- web-ui/src/app/pages/page-discussion/page-discussion.component.html
- web-ui/src/app/pages/page-discussion/page-discussion.component.ts
- web-ui/src/app/services/catalogue.service.ts
- web-ui/src/app/services/post.service.ts
We can now see the different discussions.
> update messenger and discussion

- README.md
- web-ui/package-lock.json
keycloak user registration and main readme update
> add user registration and update readme

- statistic-service/README.md
- statistic-service/src/main/java/api/StatisticRestService.java
- statistic-service/src/main/java/domain/model/StatisticItem.java
- statistic-service/src/main/java/domain/service/StatisticServiceImpls.java
- statistic-service/src/test/java/api/StatisticRestServiceTest.java
- statistic-service/src/test/java/api/msg/StatisticConsumerTest.java
- statistic-service/src/test/java/domain/service/StatisticServiceImplTest.java
Added conditions for categories and updated Readme
> Loan herault

- ad-service/src/main/java/domain/model/Annonce.java
- ad-service/src/main/java/domain/service/AnnonceServiceImpl.java
- ad-service/src/test/java/domain/service/AnnonceServiceImplTest.java
- items-service/src/main/java/domain/service/ItemServiceImpl.java
- messanger-service/src/main/java/domain/service/MessengerServiceImpl.java
- messanger-service/src/test/java/domain/service/MessengerServiceImplTest.java
messanger-service code coverage for domain should be 100% 
there is more code coverage for domain in ad-service
the state in ad-service is String
in item-service getbysearch will only extract items which are not sold yet
> I did my assignements 

- messanger-service/src/main/resources/project-defaults.yml
- web-ui/src/app/pages/catalogue/filters/filters.component.html
- web-ui/src/app/pages/page-achat/page-achat.component.ts
- web-ui/src/app/pages/profil/vente-perso/vente-perso.component.html
> Adrien chabert

- web-ui/src/app/pages/catalogue/body-catalogue/body-catalogue.component.html
- web-ui/src/app/pages/catalogue/filters/filters.component.html
- web-ui/src/app/pages/catalogue/filters/filters.component.ts
- web-ui/src/app/pages/home/quick-search/quick-search.component.html
- web-ui/src/app/pages/nav-bar/nav-bar.component.html
- web-ui/src/app/pages/page-vente/page-vente.component.html
- web-ui/src/app/pages/profil/page-profil/page-profil.component.html
Some input type has been changed to number. Some colors are changed.
> color panel changed

- items-service/src/main/java/api/ItemRestService.java
- statistic-service/src/main/java/api/StatisticRestService.java
- statistic-service/src/main/java/api/msg/StatisticConsumer.java
- statistic-service/src/main/java/domain/service/StatisticServiceImpls.java
- web-ui/src/app/pages/home/carousel-item/carousel-item.component.ts
- web-ui/src/app/services/catalogue.service.ts
category shown in the highlight now depends on the user statistic
> fix higlight

- items-service/src/main/java/api/ItemRestService.java
- statistic-service/src/main/java/api/StatisticRestService.java
- statistic-service/src/main/java/domain/service/StatisticServiceImpls.java
- web-ui/src/app/pages/home/carousel-item/carousel-item.component.ts
- web-ui/src/app/pages/modif-item/modif-item.component.ts
- web-ui/src/app/pages/page-achat/page-achat.component.ts
- web-ui/src/app/pages/profil/modify-item/modify-item.component.ts
- web-ui/src/app/services/catalogue.service.ts
add highlights if new user
item stat does no more increment if user click on his item
> fix highlights

- web-ui/src/app/pages/annonce/annonce.component.html
- web-ui/src/app/pages/annonce/annonce.component.scss
- web-ui/src/app/pages/catalogue/body-catalogue/body-catalogue.component.html
- web-ui/src/app/pages/footer/footer.component.html
- web-ui/src/app/pages/footer/footer.component.scss
- web-ui/src/app/pages/home/annonce-bottom/annonce-bottom.component.html
- web-ui/src/app/pages/home/carousel-item/carousel-item.component.html
> update web interface

- web-ui/src/app/pages/ajouter-annonce/ajouter-annonce.component.html
- web-ui/src/app/pages/ajouter-annonce/ajouter-annonce.component.scss
- web-ui/src/app/pages/messagerie/messagerie.component.html
- web-ui/src/app/pages/page-discussion/page-discussion.component.html
- web-ui/src/app/pages/page-vente/page-vente.component.html
- web-ui/src/app/pages/page-vente/page-vente.component.ts
> web interface
